### ISSUE TITLE
Reconciliation API  - iteration 2

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-reconciliation#10]
This issue is to work on this document https://docs.google.com/document/d/10eiOqials4PDipSw3zhNYTw_UbE0W0SuUk7nIAbMHxM/edit#heading=h.qbm5wo48afoq

**Comment by saumier** [comment]
@saumier Note to myself to review comments in doc.

**Comment by saumier** [comment]
@sahalali Please complete iteration 2 setting up of tests so we can proceed to iteration 3 in issue #13

**Comment by saumier** [comment]
@sahalali Is this ready for me to review? If so, please assign to me. Thx.

**Comment by sahalali** [comment]
The unit testing in closed environment is set. This is integrated with the CICD.
