### ISSUE TITLE
Recon API - First Iteration plan

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-reconciliation#2]
The Artsdata Reconciliation API needs a majour upgrade to keep pace with the needs of Footlight CMS and Footlight Console, as well as other clients like "I want to showcase" that wish to reconcile entities with Artsdata.

This issue is to work on this document https://docs.google.com/document/d/10eiOqials4PDipSw3zhNYTw_UbE0W0SuUk7nIAbMHxM/edit#heading=h.qbm5wo48afoq

Please complete assigned tasks inside the doc by checking the tasks's checkbox in the doc when completed.

Here is an updated version of the [W3C WG Spec](https://reconciliation-api.github.io/specs/draft/ ) that I worked with the community group.  There are still unmerged changes that I am requesting, but we can work with this version and we can continue to monitor changes.

**Comment by sahalali** [comment]
The plan for the first iteration looks good to me.

**Comment by sahalali** [comment]
The test environment is up and running.
Swagger documentation: http://3.99.192.137:3000/api
