### ISSUE TITLE
Add dbo:Agent to new Reconciliation service

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-reconciliation#20]

**Comment by sahalali** [comment]
Please review this issue:

Sample query
https://35.183.160.6/reconcile?queries=%7B%20%22queries%22%3A%20%5B%20%7B%20%22type%22%3A%20%22dbo%3AAgent%22%2C%20%22limit%22%3A%202%2C%20%22conditions%22%3A%20%5B%20%7B%20%22matchType%22%3A%20%22name%22%2C%20%22v%22%3A%20%22Roy%22%20%7D%20%5D%20%7D%20%5D%20%7D

**Comment by saumier** [comment]
@sahalali The test bench should be working with this:
https://culturecreates.github.io/testbench/#/client/https%3A%2F%2F35.183.160.6%2Freconciliation

I think there is a problem with the endpoints for the new reconciliation service that are not following the spec. I remember we have some confusion around the manifest endpoint versus the endpoint to make a query.

Compare with https://culturecreates.github.io/testbench/#/client/https%3A%2F%2Fapi.artsdata.ca%2Frecon

Also, please change the name of dbo:Agent to "Person or Organization/Group" like in my version 0.2.

```
 {
      "id": "dbo:Agent",
      "name": "Person or Organization/Group"
    }
```
