### ISSUE TITLE
Duplicate found in Artsdata for person Martin Vachon: K2-4876 and K12-250.

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/artsdata-reconciliation#22]
Here are some useful links [K2-4876](http://kg.artsdata.ca/resource/K2-4876). and [K12-250.](http://kg.artsdata.ca/resource/K12-250)

**Comment by saumier** [comment]
@tammy-culture The entity [K2-4876](http://kg.artsdata.ca/resource/K2-4876) is already marked as a duplicate of [K12-250](http://kg.artsdata.ca/resource/K12-250) discovered 2023-12-15.

What tool did you use to search for Martin Vachon to get K2-4876?

**Comment by saumier** [comment]
Transferted to https://github.com/artsdata-stewards/support-issues/issues/5
